### ISSUE TITLE
FFmpeg processes or camera may not release properly

### ISSUE THREAD

**Issue by btelman96** [btelman96/letsrobot-android#130]
One user and I have noticed issues when restarting the robot sometimes without fully killing the app, where the camera and mic will not start

**Comment by btelman96** [comment]
```
2019-05-26 00:12:38.767 31723-32077/tv.letsrobot.controller.android D/FFmpeg: Running publishing updates method
2019-05-26 00:12:38.782 31723-31723/tv.letsrobot.controller.android D/invoke: AudioComponent : INTERMITTENT
2019-05-26 00:12:38.782 31723-31723/tv.letsrobot.controller.android D/invoke: AudioComponent : STABLE
2019-05-26 00:12:38.899 31723-4555/tv.letsrobot.controller.android D/invoke: MainSocketComponent : STABLE
2019-05-26 00:12:38.941 31723-4560/tv.letsrobot.controller.android D/invoke: ChatSocketComponent : STABLE
2019-05-26 00:12:38.963 31723-3715/tv.letsrobot.controller.android E/CameraCaptureSession: Session 0: Exception while stopping repeating: 
    android.hardware.camera2.CameraAccessException: CAMERA_DISCONNECTED (2): cancelRequest:296: Camera device no longer alive
        at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:660)
        at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:95)
        at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1001)
        at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:391)
        at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:569)
        at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:237)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: android.os.ServiceSpecificException: cancelRequest:296: Camera device no longer alive (code 4)
        at android.os.Parcel.readException(Parcel.java:1957)
        at android.os.Parcel.readException(Parcel.java:1889)
        at android.hardware.camera2.ICameraDeviceUser$Stub$Proxy.cancelRequest(ICameraDeviceUser.java:366)
        at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:93)
        at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1001) 
        at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:391) 
        at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:569) 
        at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:237) 
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
2019-05-26 00:12:39.369 31723-4428/tv.letsrobot.controller.android D/invoke: CameraComponent : ERROR
2019-05-26 00:12:39.369 31723-4428/tv.letsrobot.controller.android W/System.err: com.github.hiteshsondhi88.libffmpeg.exceptions.FFmpegCommandAlreadyRunningException: FFmpeg command is already running, you are only allowed to run 4 commands at a time
2019-05-26 00:12:39.369 31723-4428/tv.letsrobot.controller.android W/System.err:     at com.github.hiteshsondhi88.libffmpeg.FFmpeg.execute(FFmpeg.java:70)
2019-05-26 00:12:39.370 31723-4428/tv.letsrobot.controller.android W/System.err:     at tv.letsrobot.android.api.components.camera.CameraBaseComponent.bootFFmpeg(CameraBaseComponent.kt:181)
2019-05-26 00:12:39.370 31723-4428/tv.letsrobot.controller.android W/System.err:     at tv.letsrobot.android.api.components.camera.CameraBaseComponent.tryBootFFmpeg(CameraBaseComponent.kt:155)
2019-05-26 00:12:39.370 31723-4428/tv.letsrobot.controller.android W/System.err:     at tv.letsrobot.android.api.components.camera.CameraBaseComponent.processCamera(CameraBaseComponent.kt:87)
2019-05-26 00:12:39.370 31723-4428/tv.letsrobot.controller.android W/System.err:     at tv.letsrobot.android.api.components.camera.CameraBaseComponent.handleMessage(CameraBaseComponent.kt:76)
2019-05-26 00:12:39.370 31723-4428/tv.letsrobot.controller.android W/System.err:     at tv.letsrobot.android.api.interfaces.Component$handler$1.handleMessage(Component.kt:30)
2019-05-26 00:12:39.370 31723-4428/tv.letsrobot.controller.android W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:101)
2019-05-26 00:12:39.371 31723-4428/tv.letsrobot.controller.android W/System.err:     at android.os.Looper.loop(Looper.java:164)
2019-05-26 00:12:39.371 31723-4428/tv.letsrobot.controller.android W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:65)
```
